#!/usr/bin/env bash

set -e
export VIDEOCLI_WORKDIR=$(cd $(dirname $0) && pwd)
export VIDEOCLI_LOGDIR=${VIDEOCLI_WORKDIR}/.logs
. "$VIDEOCLI_WORKDIR/common"

mkdir ${VIDEOCLI_LOGDIR} 2> /dev/null || true

cli_help () {
  cli_name=${0##*/}
  echo "
$cli_name
Video edit CLI - Wrapper for ffmpeg
Version: $(cat $VIDEOCLI_WORKDIR/VERSION)
Usage: $cli_name [command]
Commands:
  cut       Cut video input using same audio and video codecs.
  *         Help
"
  exit 1
}

case "$1" in
  cut|c)
    shift
    "$VIDEOCLI_WORKDIR/commands/cut" "$@" | tee -ia "$VIDEOCLI_LOGDIR/cut_last.log"
    ;;
  compress)
    shift
    "$VIDEOCLI_WORKDIR/commands/compress" "$@" | tee -ia "$VIDEOCLI_LOGDIR/compress_last.log"
    ;;
  *)
    cli_help
    ;;
esac
