#!/usr/bin/env bash

set -e
. "$VIDEOCLI_WORKDIR/common"

cli_help_deploy () {
  echo "
Command: cut
Usage:
  cut <input_file> [--o <output_file>] [--p <extra_params>] [--d]

Description:
  Cuts a video file <input_file> using the same audio and video codec.

Options:
  --o <output_file>
        If not present, the output is saved with the same
        name and extension as <input_file>, followed by _cut.
        Example:
            the output of cut ../input.mp4 will be saved as ../input_cut.mp4

    --p <extra_params>
        String of params that is directly passed to ffmpeg command.
    --d
        Only prints ffmpeg command. For debug purposes.
"

  exit 1
}


[ ! -n "$1" ] && cli_help_deploy
input_file=$1
extra_params=""
output_file=""
debug=false

# Read parameters
while [ $# -gt 0 ]; do
    if [[ $1 == *"--p" ]]; then
        extra_params="$2"
    elif [[ $1 == *"--o" ]]; then
        output_file="$2"
    elif [[ $1 == *"--d" ]]; then
        debug=true
    fi

  shift
done

if [ ! -n "$output_file" ]; then
    default_output $input_file "cut"
fi

cli_log "Cut BEGIN with parameters
    input_file=$input_file
    output_file=$output_file
    extra_params=$extra_params"

command="ffmpeg -i $input_file -vcodec copy -acodec copy ${extra_params} $output_file"
if [[ "$debug" = true ]]; then
    echo $command
else
    eval $command
fi

cli_log "Cut END"
